gui:
  scrollHeight: 15
customCommands:
  - key: "W"
    prompts:
      - type: "input"
        title: "Commit"
        initialValue: ""
    context: "files"
    command: git commit -m "{{index .PromptResponses 0}}" --no-verify
    description: "Commit changes without pre-commit hook and prefix"
