[[manager.prepend_keymap]]
on = "p"
run = "plugin smart-paste"
desc = "Paste into the hovered directory or CWD"

[[manager.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on = ["g", "r"]
run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'
desc = "Navigate to git root"

[[manager.prepend_keymap]]
on = "k"
run = "plugin arrow -1"

[[manager.prepend_keymap]]
on = "j"
run = "plugin arrow 1"

[[manager.prepend_keymap]]
on = "m"
run = "plugin toggle-pane min-preview"
desc = "Minimise preview pane"

[[manager.prepend_keymap]]
on = "M"
run = "plugin toggle-pane max-preview"
desc = "Maximise preview pane"
