[manager]
prepend_keymap = [
  { on = "p", run = "plugin smart-paste", desc = "Paste into the hovered directory or CWD" },
  { on = "l", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
  { on = [
    "g",
    "r",
  ], run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"', desc = "Go to git root" },
  { on = "k", run = "plugin arrow -1" },
  { on = "j", run = "plugin arrow 1" },
  { on = ">", run = "plugin toggle-pane min-preview", desc = "Minimise preview pane" },
  { on = "<", run = "plugin toggle-pane max-preview", desc = "Maximise preview pane" },
  { on = [
    'g',
    'G',
  ], run = 'plugin lazygit', desc = 'Run lazygit' },
  { on = "F", run = "plugin fzf", desc = "Jump to a file/directory via fzf" },
  { on = [
    "g",
    "c",
  ], run = "cd ~/.config", desc = "Go to ~/.config" },
  { on = [
    "g",
    "d",
  ], run = "cd ~/Downloads", desc = "Go to ~/Downloads" },
  { on = [
    "g",
    "i",
  ], run = 'cd ~/Library/Mobile\ Documents/com~apple~CloudDocs', desc = "Go to iCloud Drive" },
  { on = [
    "'",
  ], run = "plugin bookmarks jump", desc = "Jump to a bookmark" },
  { on = [
    "m",
  ], run = "plugin bookmarks save", desc = "Save current position as a bookmark" },
  { on = [
    "'",
  ], run = "plugin bookmarks jump", desc = "Jump to a bookmark" },
  { on = [
    "b",
    "d",
  ], run = "plugin bookmarks delete", desc = "Delete a bookmark" },
  { on = [
    "b",
    "D",
  ], run = "plugin bookmarks delete_all", desc = "Delete all bookmarks" },
  { on = [
    "\\",
    "p",
    "s",
  ], run = "plugin projects save", desc = "Save current project" },
  { on = [
    "\\",
    "p",
    "l",
  ], run = "plugin projects load", desc = "Load project" },
  { on = [
    "\\",
    "p",
    "P",
  ], run = "plugin projects load_last", desc = "Load last project" },
  { on = [
    "\\",
    "p",
    "d",
  ], run = "plugin projects delete", desc = "Delete project" },
  { on = [
    "\\",
    "p",
    "D",
  ], run = "plugin projects delete_all", desc = "Delete all projects" },
]
