format = """
$directory\
$git_branch\
$nodejs\
$ruby\
$rust\
$golang\
$php\
$time\
\n$character"""

[c]
symbol = ""
format = '[$symbol ($version)]($style)'

[conda]
symbol = ""
format = '[$symbol ($version)]($style)'

[directory]
read_only = " 󰌾"

[elixir]
symbol = ""
format = '[$symbol ($version)]($style)'

[git_branch]
symbol = ""
format = '[$symbol $branch(:$remote_branch)]($style) '

[golang]
symbol = ""
format = '[$symbol ($version)]($style)'

[hostname]
ssh_symbol = ""

[java]
symbol = ""
format = '[$symbol ($version)]($style)'

[kotlin]
symbol = ""
format = '[$symbol ($version)]($style)'

[lua]
symbol = ""
format = '[$symbol ($version)]($style)'

[nodejs]
symbol = ""
format = '[$symbol ($version)]($style)'

[perl]
symbol = ""
format = '[$symbol ($version)]($style)'

[php]
symbol = ""
format = '[$symbol ($version)]($style)'

[python]
symbol = ""
format = '[$symbol ($version)]($style)'

[ruby]
symbol = ""
format = '[$symbol ($version)]($style)'

[rust]
symbol = "󱘗"
format = '[$symbol ($version)]($style)'

[time]
disabled = false
time_format = "%R"             # Hour:Minute Format
style = '#a0a9cb'
format = '[  $time ]($style)'

[scala]
symbol = ""
format = '[$symbol ($version)]($style)'

[swift]
symbol = ""
format = '[$symbol ($version)]($style)'

[zig]
symbol = ""
format = '[$symbol ($version)]($style)'

[gradle]
symbol = ""
format = '[$symbol ($version)]($style)'
